### ISSUE TITLE
 creating two HiveContext in two separate test cases fail

### ISSUE THREAD

**Issue by dzhao** [holdenk/spark-testing-base#106]
Spark 1.5.0
I have two test class. Each separately creates a HiveContext. 
If I just run one test case the test case runs fine.
If i run both use ./sbt test
then I got this error
 ERROR XSDB6: Another instance of Derby may have already booted the database /Users/dzhao/Customer-Intelligence/AcctDtl/metastore_db.

I suspect first hivecontext is not properly cleaned up in time?

**Comment by mahmoudhanafy** [comment]
I think it will be better if you create your `HiveContext` only one time before all test cases using interface `BeforeAndAfterAll`.

**Comment by dzhao** [comment]
hmm.. Are you saying I set up one Hivecontext for all the test suites I run(I will have more than one suite for sure). But BeforeAndAfterAll seems to only work for one suite?

**Comment by mahmoudhanafy** [comment]
I thought you only have test cases inside one class. We have a problem like this before. I think I will create an interface that will provide SparkContext and SQLContext.

For now you can extends `DataFrameSuiteBase` multiple times and you can access the sqlContext from there.

**Comment by dzhao** [comment]
thanks. that works. I guess DataFrameSuiteBase will be just fine since you can always get sparkContext from sqlContext.
Also, can we change sqlContext from def to lazy val?
In my case, I always do
import sqlContext.implicits._
but sqlContext being a def prevents me from doing that. I have to assign sqlContext to another lazy val and then do the import.

It just feels redundant.

**Comment by mahmoudhanafy** [comment]
That's a good idea. I will create a PR with your suggestion.

**Comment by pavlov99** [comment]
Thanks for the update!
