### ISSUE TITLE
maven version info on wiki is wrong

### ISSUE THREAD

**Issue by sarunkums** [holdenk/spark-testing-base#107]
should be:

libraryDependencies += "com.holdenkarau" % "spark-testing-base_2.10" % "1.6.1_0.3.3"

is currently showing

"com.holdenkarau" %% "spark-testing-base" % "1.6.1_0.3.3"

**Comment by mahmoudhanafy** [comment]
I think `"com.holdenkarau" %% "spark-testing-base" % "1.6.1_0.3.3"` working fine. Using `%%` adds your scala version to the library name, So `x %% y % z = x % y_scalaVersion % z`

It's used [here](https://github.com/holdenk/spark-validator/blob/master/build.sbt) in another project, and it's working fine.

**Comment by sarunkums** [comment]
interesting, will give that a try, thanks again!
