### ISSUE TITLE
Release 0.3.3 not tagged in GitHub Repo

### ISSUE THREAD

**Issue by jthelin** [holdenk/spark-testing-base#109]
The "current" release of `spark-testing-base` is listed as 0.3.3 in the ReadMe and spark-packages page.
http://spark-packages.org/package/holdenk/spark-testing-base

However, that 0.3.3 release is not tagged in the GitHub repo. 
https://github.com/holdenk/spark-testing-base/releases

Would you kindly add that `v0.3.3` tag to the repo so it shows up properly on the Releases page?

I believe the 0.3.3 tag should be on ecf02f4483edf6e07d1cd89e39e1b1c0acaec44b ?

Thanks,
- Jorgen

**Comment by mahmoudhanafy** [comment]
Thanks for pointing to this. I will add it.
