### ISSUE TITLE
Add DataFrame approximate equality operation

### ISSUE THREAD

**Issue by holdenk** [holdenk/spark-testing-base#12]
Add an API to do quick DataFrame comparisions. We should allow users to supply a custom equality operator for floats.

**Comment by svenhofstede** [comment]
Has this been implemented [here](https://github.com/holdenk/spark-testing-base/blob/master/src/main/1.3/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala#L109)?

**Comment by holdenk** [comment]
Good point, let me close the issue.
