### ISSUE TITLE
Cannot resolve symbol `test` for version 2.0

### ISSUE THREAD

**Issue by octaviantuchila14** [holdenk/spark-testing-base#126]
I have added the following to my `build.sbt`:

> "com.holdenkarau" %% "spark-testing-base" % "2.0.0_0.4.4" % "test"

I have the following test:

> import com.holdenkarau.spark.testing._
> 
> class test extends DatasetSuiteBase {
>   test("simple test") {
>     val sqlCtx = sqlContext
>     import sqlCtx.implicits._
> 
> ```
> val input1 = sc.parallelize(List(1, 2, 3)).toDS
> assertDatasetEquals(input1, input1) // equal
> 
> val input2 = sc.parallelize(List(4, 5, 6)).toDS
> intercept[org.scalatest.exceptions.TestFailedException] {
>   assertDatasetEquals(input1, input2) // not equal
> }
> ```
> 
>   }
> }

However, I get:

> Cannot resolve symbol test
> Cannot resolve symbol intercept

**Comment by holdenk** [comment]
Ah yes, so you will need to also extend a suite (e.g. `import org.apache.spark.sql.Row
import org.scalatest.FunSuite

class SampleDataFrameTest extends FunSuite with DataFrameSuiteBase {
`)

**Comment by holdenk** [comment]
Closing for now since I believe the issue has been resolved (must mix in funsuite or similar).
