### ISSUE TITLE
provide reset to localRootDirs per each test

### ISSUE THREAD

**Issue by IgorBerman** [holdenk/spark-testing-base#13]
Hi,
1) thanks for the project!
2) despite the fact that I'm writing tests in java with junit(so I haven't succeeded to use `LocalSparkContext` trait), I think there is some scenario which can be improved:

suppose I have several tests in test suite, and suppose I have `@BeforeEach` & `@AfterEach` which creates and deletes temp dir(so that each test will have separate env, separate local dirs etc).
I've tried to set `spark.local.dir` with something like `sparkConf.set("spark.local.dir", tempDir+"/spark");`
it works, but only for 1'st test, probably due to how `Utils.getOrCreateLocalRootDirs` method is implemented, it has specific comment that it caches local dir.
so there is another method in Utils 
```Scala
/** Used by unit tests. Do not call from other places. */
  private[spark] def clearLocalRootDirs(): Unit = {
    localRootDirs = null
  }
```
which can clean local root dir, however it's private, so my test can't use it.
might be you want to add call to clearLocalRootDirs? into your LocalSparkContext stop method?
anyway would like to hear what is the best way to approach this problem? might be I need to open jira in spark repo to open clearLocalRootDirs to public access?

ps: I needed to investigate it because I saw that there are directories that aren't cleaned up after tests(because 2nd in suite test reuses local dir that was deleted at the end of 1'st test and thus recreating the dir)

**Comment by mahmoudhanafy** [comment]
Sorry for the late reply. Could you please add the code you used, to be able to regenerate this temp dir problem ?
