### ISSUE TITLE
build for spark 1.6.2

### ISSUE THREAD

**Issue by samehraban** [holdenk/spark-testing-base#131]
Apparently there is no package for spark 1.6.2 on maven.

**Comment by zouzias** [comment]
I just created PR #133 for this.

**Comment by samehraban** [comment]
@holdenk Could you please take a look at this?

**Comment by zouzias** [comment]
Hi @samehraban , PR #133 is merged and the artifacts fro 1.6.2 are released. This issue can be closed.

**Comment by samehraban** [comment]
@zouzias They're not published to maven repository yet.

**Comment by zouzias** [comment]
http://repo1.maven.org/maven2/com/holdenkarau/spark-testing-base_2.11/1.6.2_0.4.5/

**Comment by samehraban** [comment]
Oops. I was checking 2.10 since spark 1.6.x prebuilt comes with scala 2.10.

**Comment by zouzias** [comment]
This ticket can be closed, do you agree @samehraban?
