### ISSUE TITLE
java.io.NotSerializableException: org.scalatest.Assertions$AssertionsHelper

### ISSUE THREAD

**Issue by ksranga** [holdenk/spark-testing-base#138]
I get this error when trying to test a function that does group by on RDD - seems related to issue 61 that was fixed a few months ago

`22:32:00.658 [sparkDriver-akka.actor.default-dispatcher-2] ERROR o.a.spark.scheduler.TaskSetManager - Failed to serialize task 3, not attempting to retry it.
java.io.NotSerializableException: org.scalatest.Assertions$AssertionsHelper
Serialization stack:
	- object not serializable (class: org.scalatest.Assertions$AssertionsHelper, value: org.scalatest.Assertions$AssertionsHelper@1881e792)
	- field (class: org.scalatest.FlatSpec, name: assertionsHelper, type: class org.scalatest.Assertions$AssertionsHelper)
	- object (class com.advisory.pic.etl.claim.replacement.OutpatientReplacementTest, OutpatientReplacementTest)
	- field (class: com.advisory.pic.etl.claim.replacement.OutpatientReplacementTest$Claim, name: $outer, type: class com.advisory.pic.etl.claim.replacement.OutpatientReplacementTest)
	- object (class com.advisory.pic.etl.claim.replacement.OutpatientReplacementTest$Claim, Claim(A1,1,11/14/2015,11/01/2015,1))
	- element of array (index: 0)
	- array (class [Lcom.advisory.pic.etl.claim.replacement.OutpatientReplacementTest$Claim;, size 1)
	- field (class: scala.collection.mutable.WrappedArray$ofRef, name: array, type: class [Ljava.lang.Object;)
	- object (class scala.collection.mutable.WrappedArray$ofRef, WrappedArray(Claim(A1,1,11/14/2015,11/01/2015,1)))
	- writeObject data (class: org.apache.spark.rdd.ParallelCollectionPartition)
	- object (class org.apache.spark.rdd.ParallelCollectionPartition, org.apache.spark.rdd.ParallelCollectionPartition@694)
	- field (class: org.apache.spark.scheduler.ShuffleMapTask, name: partition, type: interface org.apache.spark.Partition)
	- object (class org.apache.spark.scheduler.ShuffleMapTask, ShuffleMapTask(0, 3))`

**Comment by ksranga** [comment]
There was an issue with my code that led to this failure. Closing the thread.

**Comment by saatvikshah1994** [comment]
I'm facing the same error - what was the bug you faced?
