### ISSUE TITLE
Build for Spark 2.0.1

### ISSUE THREAD

**Issue by zouzias** [holdenk/spark-testing-base#145]
Hi there,

Is anyone working on the build for Spark 2.0.1: http://spark.apache.org/docs/latest/index.html ? If not, should I initiate a PR on it?

**Comment by holdenk** [comment]
Sure - to add a new version just make sure to bump the version number in the current build.sbt and add it to the list of cross-build versions in the perl script. Looking forward to your PR :)

**Comment by zouzias** [comment]
Fixed in #146 and artifacts are release on maven: http://repo1.maven.org/maven2/com/holdenkarau/spark-testing-base_2.11/2.0.1_0.4.7/
