### ISSUE TITLE
hive exception with Spark2

### ISSUE THREAD

**Issue by samudurand** [holdenk/spark-testing-base#148]
Hi, I am using version : 2.0.0_4.7

And I am getting Hive errors when attempting to use the sparkSession 

```
A needed class was not found. This could be due to an error in your runpath. Missing class: org/apache/hadoop/hive/conf/HiveConf$ConfVars
java.lang.NoClassDefFoundError: org/apache/hadoop/hive/conf/HiveConf$ConfVars
    at com.holdenkarau.spark.testing.DataFrameSuiteBaseLike$class.newBuilder$1(DataFrameSuiteBase.scala:67)
    at com.holdenkarau.spark.testing.DataFrameSuiteBaseLike$class.sqlBeforeAllTestCases(DataFrameSuiteBase.scala:81)
```

I am not giving any of my code since it happens during the DataFrameSuitBase execution before any test runs. Any idea what dependency I might be missing ?

**Comment by simplesteph** [comment]
Have you managed to resolve this?

**Comment by samudurand** [comment]
In fact I did, the documentation does not specifies that you have to add Spark-Hive to your dependencies for this library to work. Simply add it as a test dependency and it will fix the issue 

```
libraryDependencies += "org.apache.spark" %% "spark-hive"       % "2.0.0" % "test"
```

**Comment by samelamin** [comment]
Thanks @samudurand! I was stuck with this for about 20 mins!

**Comment by antonkulaga** [comment]
It is stupid that it needs have! Most of the people use spark.sql but not hive!

**Comment by holdenk** [comment]
We recently added an implicit to make it easier to disable hive support. That being said Spark SQL is often used along with hive support.

**Comment by antonkulaga** [comment]
```scala
  override implicit def enableHiveSupport: Boolean = false
```
does not help. Even after clean rebuild it gives following errors if I do not have hive dependency included.
```
[info] test.ExtendedFeaturesTest *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: org/apache/hadoop/hive/conf/HiveConf$ConfVars
[info]   at com.holdenkarau.spark.testing.DataFrameSuiteBaseLike$class.newBuilder$1(DataFrameSuiteBase.scala:77)
[info]   at com.holdenkarau.spark.testing.DataFrameSuiteBaseLike$class.sqlBeforeAllTestCases(DataFrameSuiteBase.scala:106)
[info]   at test.AdamTestBase.com$holdenkarau$spark$testing$DataFrameSuiteBase$$super$sqlBeforeAllTestCases(AdamTestBase.scala:17)
[info]   at com.holdenkarau.spark.testing.DataFrameSuiteBase$class.beforeAll(DataFrameSuiteBase.scala:42)
[info]   at test.AdamTestBase.beforeAll(AdamTestBase.scala:17)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at test.AdamTestBase.run(AdamTestBase.scala:17)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: org.apache.hadoop.hive.conf.HiveConf$ConfVars
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info]   at com.holdenkarau.spark.testing.DataFrameSuiteBaseLike$class.newBuilder$1(DataFrameSuiteBase.scala:77)
[info]   at com.holdenkarau.spark.testing.DataFrameSuiteBaseLike$class.sqlBeforeAllTestCases(DataFrameSuiteBase.scala:106)
[info]   at test.AdamTestBase.com$holdenkarau$spark$testing$DataFrameSuiteBase$$super$sqlBeforeAllTestCases(AdamTestBase.scala:17)
[info]   at com.holdenkarau.spark.testing.DataFrameSuiteBase$class.beforeAll(DataFrameSuiteBase.scala:42)
[info]   at test.AdamTestBase.beforeAll(AdamTestBase.scala:17)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
```

**Comment by kurtmaile** [comment]
Hi all, are people still experiencing this issue?  Ive tried both adding hive library to dedpendencies and the override but still get the same error from this issue?

Thanks

**Comment by kurtmaile** [comment]
p.s - hope you are having fun in Melbourne Holden!

**Comment by kurtmaile** [comment]
scratch that got it to work yay!

**Comment by antonkulaga** [comment]
How?
In my case override did not work. I also had sparkl sql tests (with hive
dep) failing while the same code worked well in spark notebook. I gey a
feeling thay there is something wrong with dataframe testbase..

On Aug 3, 2017 20:27, "kurtmaile" <notifications@github.com> wrote:

scratch that got it to work yay!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/holdenk/spark-testing-base/issues/148#issuecomment-320036365>,
or mute the thread

**Comment by goutam-git** [comment]
I am facing the same issue...has anyone been able to resolve it.I have included spark-hive as part of dependency

  "org.apache.spark" %% "spark-core" % "1.6.0-cdh5.8.4" % "provided",
  "org.apache.spark" %% "spark-hive" % "1.6.0-cdh5.8.4" % "provided",
  "org.apache.spark" %% "spark-sql" % "1.6.0-cdh5.8.4" % "provided",
  "com.holdenkarau" %% "spark-testing-base" % "1.6.0_0.8.0" % "test",

**Comment by mazelx** [comment]
Same problem here... tried to add spark-hive dependency and override enableHiveSupport with no luck so far

**Comment by goutam-git** [comment]
resolved the error...
   please add the following  hadoop dependencies  along with spark dependencies
       "org.apache.hadoop" % "hadoop-core" % "2.6.0-mr1-cdh5.8.4" % "provided",
      "org.apache.hadoop" % "hadoop-common" % "2.6.0-cdh5.8.4" % "provided",
      "org.apache.hadoop" % "hadoop-hdfs" % "2.6.0-cdh5.8.4" % "provided",
      "org.apache.hadoop" % "hadoop-mapreduce-client-core" % "2.6.0-cdh5.8.4" % "provided",
      "org.apache.hadoop" % "hadoop-mapreduce-client-common" % "2.6.0-cdh5.8.4" % "provided",
      "org.apache.hadoop" % "hadoop-mapreduce-client-jobclient" % "2.6.0-cdh5.8.4" % "provided",
      "org.apache.hadoop" % "hadoop-yarn-api" % "2.6.0-cdh5.8.4" % "provided",
      "org.apache.hadoop" % "hadoop-yarn-common" % "2.6.0-cdh5.8.4" % "provided",
      "org.apache.hadoop" % "hadoop-yarn-client" % "2.6.0-cdh5.8.4" % "provided",

**Comment by geoHeil** [comment]
This is related to https://issues.apache.org/jira/browse/SPARK-22918 due to the upgrade of derby. Apparently some change in security configuration is required.

**Comment by chrisalbright** [comment]
Adding dependencies only so your testing libraries will work is the wrong answer.

Having no dependency on Hive in my app, and being forced to depend on them for tests seems backwards. Did I miss the docs somewhere that declared this was necessary?

@holdenk, I see your message from last year indicating it was easy to override the behavior. Please forgive my ignorance, but overriding `enableHiveSupport` to be false doesn't work for me, at least the way I'm trying.

Could you provide an example of disabling hive support so I don't have to manage the additional and un-expected dependency?

Also, would you be open to a pull request making the dependency optional and explicit?

**Comment by JohnRoesler** [comment]
Could anyone share an update on how you resolved this? I'm facing the same issue and seeing folks comments around overriding not working I'd like to understand how to solve. Thank you!

**Comment by MrPowers** [comment]
@JohnRoesler - The easiest work-around is to add the `spark-hive` dependency to your `build.sbt` file: 

```
libraryDependencies += "org.apache.spark" %% "spark-hive"       % "2.0.0" % "test"
```

You can also switch to [spark-fast-tests](https://github.com/MrPowers/spark-fast-tests/) if you'd like to manage the SparkSession separately from the testing framework and sidestep the hive dependency entirely.
