### ISSUE TITLE
Error with Spark 2.0

### ISSUE THREAD

**Issue by SrikanthTati** [holdenk/spark-testing-base#151]
Hello,

I tried the sample RDDGenerator with Spark 2.0
```
class StreamingEventUpdateTest extends FunSuite with SharedSparkContext with Checkers {
  test("map should not change number of elements") {
    //implicit val generatorDrivenConfig = PropertyCheckConfig(minSize = 10, maxSize = 20)
    val property =
      forAll(RDDGenerator.genRDD[String](sc)(Arbitrary.arbitrary[String])) {
        rdd => rdd.map(_.length).count() == rdd.count()
       }
    check(property)
  }

```
And got this error..

> [info] - map should not change number of elements *** FAILED ***
> [info]   IncompatibleClassChangeError was thrown during property evaluation.
> [info]     Message: Found class org.scalacheck.Gen, but interface was expected
> [info]     Occurred when passed generated values (
> [info]
> [info]     )

This is what I have in sbt

>   "org.scalatest" %% "scalatest" % "3.0.0" % "test",
>   "org.mockito" % "mockito-all" % "1.10.19" % "test",
>   "com.holdenkarau" %% "spark-testing-base" % "2.0.1_0.4.7" % "test"
>       excludeAll( ExclusionRule(organization = "io.netty", name = "netty") ),

 
Any suggestions on what is missing?

**Comment by samudurand** [comment]
I never tried using checkers but maybe it require you to explicitely import Scalacheck ?

**Comment by holdenk** [comment]
The release of `sparkTestingBase` you are using is build with scalatest 2.2.6 and you are importing 3.0.0 so you will run into errors like this. You can work around this by using the same version of ScalaTests as spark-testing-base, I'll look at updating the version of scalatest we use in the future.
