### ISSUE TITLE
PySpark - Missing HiveContext Test Case

### ISSUE THREAD

**Issue by afranzi** [holdenk/spark-testing-base#153]
Python Test Library doesn't provide a solution for HiveContext.

It should try to share HiveContext across tests or provide a way to start **metastore_db** in different folders to avoid **lock** problems.

Should spark-testing-base upgraded to Spark 2.0.0 using SparkSessions and supporting **enableHiveSupport()**?

**Comment by holdenk** [comment]
This sounds like something we should add, if you've got some time to work on it yourself that would be great otherwise I'm planning on taking some time to update the Python support in the new year.

**Comment by holdenk** [comment]
So I've put a fix in for this, uses the Session uilder if its present and allows to specify the conf. Should be in 0.6 when I get to it :)

**Comment by afranzi** [comment]
Perfect. Thanks Holden!
