### ISSUE TITLE
SparkSession mocking : calls real JDBC

### ISSUE THREAD

**Issue by samudurand** [holdenk/spark-testing-base#155]
It seems that when I use DataframeSuiteBase with a writing in a JDBC sink the jdbc call is REALLY made ? is the mocking not yet done ? Or is it a bug ?

**Comment by holdenk** [comment]
These aren't mocks, rather they are test instances (so local versions of the cluster code) - so interacting with a JDBC source or sink requires that the JDBC source exist.
