### ISSUE TITLE
Support spark 2.1.0

### ISSUE THREAD

**Issue by Krever** [holdenk/spark-testing-base#158]

**Comment by holdenk** [comment]
If you want to help with this I'd be happy to review the PR (updating minor versions often isn't too difficult) otherwise I'll get to this later on this month.

**Comment by Krever** [comment]
Yeah, sure. I've assumed that major effort will be in releasing new artifact and that code change will be just bumping the spark version. But will be happy to make a PR.

**Comment by holdenk** [comment]
Yah the main thing is running the release script, but just bumping the build version & adding it to the release script and seeing if anything breaks can be done by anyone :)

**Comment by holdenk** [comment]
Just published to sonatype should hit maven central in not too long. New version is 0.5.0 :)

**Comment by ogirardot** [comment]
Thanks !

**Comment by ogirardot** [comment]
It works, 0.5.0 is up and running, this can be closed

**Comment by holdenk** [comment]
Lovely, closing - thanks ! :)
