### ISSUE TITLE
Trait for Spark Session

### ISSUE THREAD

**Issue by d80tb7** [holdenk/spark-testing-base#169]
Would it be possible to add a trait for getting hold of an initialized spark session within a test.  Either something standalone analogous to sharedsparkcontext or alternatively just a field inside dataset/framesuitebase.

**Comment by d80tb7** [comment]
I'm an idiot- this already exists as the spark variable in datasetSuiteBase.  Doh!

**Comment by bbarker** [comment]
You aren't the only idiot; probably would be worth adding something to the readme. I had something like this that threw an NPE - thought I'd found the right session:

```scala
object CsvLookupAnalyzerTest {

  implicit val spark: SparkSession = SparkSessionProvider._sparkSession

  private var analyzer: LookupAnalyzer = null

  @BeforeClass
  def setUp {
    val stream: InputStream = classOf[CsvLookupAnalyzerTest].getResourceAsStream("/test.csv")
    analyzer = new CsvLookupAnalyzer(stream, true)
  }
}```

Thanks for the hint! Hopefully I can get something working.

**Comment by minnieshi** [comment]
It helped me too. Thank you for solving your own issue @d80tb7 
The wiki page https://github.com/holdenk/spark-testing-base/wiki/SharedSparkContext only said it is possible to use spark session, but how it was not clear; and i am glad I searched in the issues.
