### ISSUE TITLE
joining DStream with different windows busts the framework

### ISSUE THREAD

**Issue by fd8s0** [holdenk/spark-testing-base#173]
Basically that, it's perfectly valid and it works to have streams with different window durations / slides joined together, however the framework will complain about it and fail.

**Comment by holdenk** [comment]
Can you paste your exception?

**Comment by holdenk** [comment]
Looking at `TransformedDStream.scala` it seems like its a hard requirement (from the Spark side) that the slides be the same, so I'm closing this for now. If there is something which says or behaves otherwise though please feel free to re-open.
