### ISSUE TITLE
org.scalatest.exceptions.TestFailedException: StructType(StructField(output,DoubleType,true)) did not equal StructType(StructField(output,DoubleType,true))

### ISSUE THREAD

**Issue by nagaral** [holdenk/spark-testing-base#177]
Even though schemas match, it throws an error. Is anyone seeing this error?

**Comment by holdenk** [comment]
huh thats weird - which version of Spark & spark-testing-base and do you have the full schema for the dataframe handy?

**Comment by nagaral** [comment]
I am using the following versions : 
Spark : 		<artifactId>spark-core_2.11</artifactId>
			<version>2.1.0</version>

spark-testing-base : 		<artifactId>spark-testing-base_2.11</artifactId>
			                        <version>2.1.0_0.6.0</version>
Here is the output I got from printSchema : (It's the same for both dataframes) 
root
 |-- output: double (nullable = true)

**Comment by holdenk** [comment]
Do you have a quick repro I can slot in? If not no stress I'll take a look.

**Comment by nagaral** [comment]
Sure. Do you just need the test case I used ?

**Comment by holdenk** [comment]
that would be lovely

**Comment by nagaral** [comment]
import com.holdenkarau.spark.testing._
import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner
import org.apache.spark.sql.types.{ StructField, StructType }
import org.apache.spark.sql.{ DataFrame, SQLContext }
import org.apache.spark.{ SparkConf, SparkContext }

case class input(output: scala.Double)

@RunWith(classOf[JUnitRunner])
class DataFrameTest extends FunSuite with DataFrameSuiteBase {

  /**
   * Set nullable property of column.
   * @param df source DataFrame
   * @param cn is the column name to change
   * @param nullable is the flag to set, such that the column is  either nullable or not
   */

  

  test("Testing Vector Selector") {
    val sqlCtx = sqlContext
    import sqlCtx.implicits._
    import org.apache.spark.ml.feature.{ RegexTokenizer, Tokenizer }
    import org.apache.spark.ml.feature._
    import org.apache.spark.ml.feature.Interaction
    import org.apache.spark.ml.feature.VectorAssembler
    import org.apache.spark.mllib.linalg.{ Vector, Vectors }
    
      def setNullableStateOfColumn(df: DataFrame, cn: String, nullable: Boolean): DataFrame = {

    // get schema
    val schema = df.schema
    // modify [[StructField] with name `cn`
    val newSchema = StructType(schema.map {
      case StructField(c, t, _, m) if c.equals(cn) => StructField(c, t, nullable = nullable, m)
      case y: StructField                          => y
    })
    // apply new schema
    df.sqlContext.createDataFrame(df.rdd, newSchema)
  }
      

    val expectedDF = spark.createDataFrame(
      Seq(
        (input(2.0)),
        (input(0.0)),
        (input(0.0)),
        (input(21.0)),
        (input(14.0)),
        (input(21.0))))
      .toDF("output")
      
      val df2 = setNullableStateOfColumn(expectedDF,"output", true )
    val assembler1 = new VectorAssembler().
      setInputCols(Array("id1", "id2", "id3", "id4", "id5", "id6", "id7")).
      setOutputCol("vec1")

    val assembled1 = assembler1.transform(df)
    val customAssembled = assembled1.select("id1", "vec1")

    val myAssembler = new VectorSelector().setInputCols(Array("id1", "vec1")).setOutputCol("output")
    val assembled2 = myAssembler.transform(customAssembled)
    assembled2.select("output").show
    val myOutput = assembled2.select("output").toDF()
    assert(myOutput,df2)
  
  }

}

**Comment by holdenk** [comment]
So my first guess from looking at this would be - does the `VectorSelector` set any metedata on the fields?

**Comment by nagaral** [comment]
That was spot on ! I didn't realize I was adding some metadata . Thanks for the very quick reply !! Really appreciate your help.

**Comment by holdenk** [comment]
Thanks for reporting this - a good thing to come out of this is we should improve the error messages here to be a bit clearer so I'll create a seperate follow up issue for that (it could be as simple as including a note about metadata may differ even if toString is equivelent).
