### ISSUE TITLE
Publish Scala 2.11 Builds to Maven Repo

### ISSUE THREAD

**Issue by jnadler** [holdenk/spark-testing-base#18]
Seems like it would be consistent with spark-core to publish both 2.10 and 2.11 builds.

Obviously this is not a very high priority, as one can just build their own.   We do :)

**Comment by mariussoutier** [comment]
:+1:

**Comment by holdenk** [comment]
Thanks for pointing this out, I'll try and get to this over the weekend (for an extra spookey halloween 2.11 release :p)

**Comment by swistaczek** [comment]
Hey @holdenk, could you please release version compiled against scala 2.11?

**Comment by holdenk** [comment]
They should be synced to maven central now (I pushed them to Sonatype OSS yesterday) and I'll update the Spark packages tonight (sadly the spark packages publishing needs to wait for maven central sync first if you are publishing to maven and I fell asleep before I did that).
