### ISSUE TITLE
add other attributes in SparkConf and run test doesn't work

### ISSUE THREAD

**Issue by feiyuyitiao** [holdenk/spark-testing-base#187]
I want to add other attributes to SparkConf after SparkContext has Costructed.  to do this I create a test class ant extends SharedSparkContext , and in my test method , I add this code e.g.
`  sc.getConf
      .set("spark.driver.allowMultipleContexts", "false")
      .set("spark.sql.allowMultipleContexts", "false")
      .set("spark.app.id", "MongoSparkConnector")
      .set("spark.mongodb.input.uri", DEFAULT_URI)
      .set("spark.mongodb.input.database", "statics")
      .set("spark.mongodb.input.collection", "room_net_info")
      .set("spark.mongodb.input.partitioner", "TestPartitioner$")
      .set("spark.mongodb.output.uri", DEFAULT_URI)
      .set("spark.mongodb.output.database", "statics")
      .set("spark.mongodb.output.collection", "room_net_info1")`
when I run the test, from output I see the attribute isn't added , to verify my code I create a main class do the same thing is Okay. 
It's there a way to dynamic add SparkCont attributes after SparkContext has Costructed?

**Comment by crothexpedia** [comment]
You can override the 'conf' def in
https://github.com/holdenk/spark-testing-base/blob/master/src/main/1.3/scala/com/holdenkarau/spark/testing/SparkContextProvider.scala

This would allow you to set the conf before it passed to sc.

**Comment by hhamalai** [comment]
Another possibility is to add your Spark related variables into system properties as all properties starting with "spark." are included in SparkConf read by the spark-testing-base.
e.g. System.setProperty("spark.mongodb.input.uri", DEFAULT_URI)

**Comment by holdenk** [comment]
Both of these present the two ways to makes the work. Modifying a running contexts config doesn't really work well in Spark outside of a few limited things.
