### ISSUE TITLE
Implement passing SparkConf to LocalSparkContext

### ISSUE THREAD

**Issue by ponkin** [holdenk/spark-testing-base#19]
Sometimes there is certain need in passing preconfigured custom SparkConf when creating SparkContext in LocalSparkContext. 
```scala
val conf: SparkContext = ...
withSpark(conf) { sc=>
 ...
}

**Comment by holdenk** [comment]
So the current supported way to do this is to override the conf, would having it as a fixture be easier for you?

**Comment by ponkin** [comment]
Oh, right! sorry for bothering you!

**Comment by holdenk** [comment]
No worries, glad to help :)
