### ISSUE TITLE
git tags that represent releases haven't been pushed to github

### ISSUE THREAD

**Issue by thomasdziedzic** [holdenk/spark-testing-base#204]
The latest release is 0.7.4 but the latest available release in git tags is v0.3.3

Having tagged releases would help me understand what changes have been made between different releases.

**Comment by holdenk** [comment]
The release aren't currently tagged but rather branched because of the way how we need to build for different versions of Spark and have the specific build file be sound by the spark-package builder. Does looking at the branches work for you?

**Comment by thomasdziedzic** [comment]
wfm
