### ISSUE TITLE
Update to Spark 1.5.1

### ISSUE THREAD

**Issue by mariussoutier** [holdenk/spark-testing-base#22]
Update to Spark 1.5.1.

**Comment by holdenk** [comment]
Done :)

**Comment by mariussoutier** [comment]
Thanks

**Comment by holdenk** [comment]
Sure thing, if theres more features you want/need just make an issue and I'm going to set aside some time this Sunday to work on the testing stuff :)

**Comment by mariussoutier** [comment]
The biggest pain right now is testing streaming jobs, so anything you could add there would be much appreciated (e.g. a helper for testing job serializability). I'll give you more feedback once the 2.11 build is published, then I'll try to migrate my production project to spark-testing-base.
