### ISSUE TITLE
Spark 2.2.2 support

### ISSUE THREAD

**Issue by ryanamiri** [holdenk/spark-testing-base#268]
I can see from issue https://github.com/holdenk/spark-testing-base/pull/264 that support has been added for Spark 2.2.2 and 2.3.2. However, it looks like the changes were never published. Are there plans to publish or was it just an oversight? 

Thanks!

**Comment by opensorceror** [comment]
+1

Guys, this would be great to have!

**Comment by serefacet** [comment]
+1

**Comment by nsutcliffe** [comment]
+1
Also looking for this 👍

**Comment by MuqadderIqbal** [comment]
Has this been published yet? Also, there is an open pull request to add support for 2.4.0 but it hasn't been merged back to master yet. Can we get that one merged and published too? It'll save me tons of headache maintaining multiple versions of spark.

**Comment by holdenk** [comment]
Sorry folks I’ll try and get this done on Monday.

**Comment by kamatsuoka** [comment]
+1

**Comment by yellowbrickc** [comment]
+10
