### ISSUE TITLE
Set Spark Config property - Python

### ISSUE THREAD

**Issue by Vzzarr** [holdenk/spark-testing-base#281]
While I was trying to use this library in Python, I needed to test a function which writes on a Postgres DB.

To do so is necessary to provide to the Spark Session the Driver to connect to Posgtres; to do so I first tried to override the `getConf()` method (as reported in the comment `Override this to specify any custom configuration.`). But apparently it doesn't work. Probably I'm not passing the value with the required syntax or whatever but after many attempts I anyway get the error `java.lang.ClassNotFoundException: org.postgresql.Driver` (typical of when the Driver Jar was not correctly downloaded through the conf parameter).

```
    def getConf(self):
        return ("spark.jars.packages", "org.postgresql:postgresql:42.1.1")

    def getConf(self):
        return {"spark.jars.packages", "org.postgresql:postgresql:42.1.1"}

    def getConf(self):
        return SparkConf()\
            .setMaster("local[*]")\
            .setAppName("test")\
            .set("spark.jars.packages", "org.postgresql:postgresql:42.1.1")
```

So I even tried to Override `the setUp()` method like that:

```
    def setUp(self):
        try:
            from pyspark.sql import Session
            self.session = Session.Builder.config("spark.jars.packages", "org.postgresql:postgresql:42.1.1")
            self.sqlCtx = self.session._wrapped
        except Exception:
            self.sqlCtx = SQLContext(self.sc)
```

But still no luck. So what I am doing wrong? How am I supposed to override the `getConf()` method?

**Comment by noleto** [comment]
In fact, `getConf()` is never called as the sqlCtx is created in the except block (you can check in debug mode with a breakpoint).
So the only way I could get rid of it was to override `setUpClass(cls)` method:

```python
 @classmethod
    def setUpClass(cls):
        """Setup a basic Spark context for testing"""
        class_name = cls.__name__
        conf = SparkConf().set("spark.jars.packages", "org.postgresql:postgresql:42.1.1")
        cls.sc = SparkContext(cls.getMaster(), appName=class_name, conf=conf)
        quiet_py4j()
```

**Comment by Vzzarr** [comment]
it worked! Thank you very much!
