### ISSUE TITLE
Executors tab in Spark UI not working

### ISSUE THREAD

**Issue by miramar-labs** [holdenk/spark-testing-base#301]
upon clicking it, I see this:

2019-09-03 19:56:06,589 WARN  [ServletHandler] [] Error for /api/v1/applications
java.lang.NoClassDefFoundError: org/glassfish/jersey/internal/inject/AbstractBinder

and nothing shows up in the tab view...

Spark 2.4.0

**Comment by datamove** [comment]
@miramar-labs Hi Aaron, did you get around empty Executors tab? same in 2.4.7

**Comment by holdenk** [comment]
This is as intended we disable some of the UI for tests, if you want the full UI run your code outside of the tests.
