### ISSUE TITLE
Cannot get sources to become available in VSCode

### ISSUE THREAD

**Issue by robbyki** [holdenk/spark-testing-base#316]
I am not sure what I'm doing wrong here but I've tried a bunch of things and I still cannot get spark testing base sources to become available within vscode. I can track down the actual jar files in `.cache/coursier/v1/https/repo1.maven.org/maven2/com/` location and I see it show up in `compile:dependencyClasspath` or `test:dependencyClasspath` but when I go to metals libraries all my folders are empty and therefore cannot jump to any of the definitions. I'm running on scala/spark 2.11/2.4.4 and using `"com.holdenkarau" %% "spark-testing-base" % "2.4.4_0.14.0"`. Also tried `withSources()` and same result.

**Comment by andy-clegg** [comment]
Having the same problem in IntelliJ. I manually downloaded this:

https://repo1.maven.org/maven2/com/holdenkarau/spark-testing-base_2.11/2.4.5_0.14.0/spark-testing-base_2.11-2.4.5_0.14.0-sources.jar

and unzipped it, and it seems to be full of compiled .class files, but no source files?

**Comment by yuxh** [comment]
@andy-clegg yes, no source code is included
