### ISSUE TITLE
Publish Spark 3 Version?

### ISSUE THREAD

**Issue by etspaceman** [holdenk/spark-testing-base#329]
Hey There - 

We are looking to upgrade our testing to use the new Spark 3 version, but it doesn't seem to be released. Can we get this published?

**Comment by wrwills** [comment]
If I could locally publish the spark 3 version that would be a start, but for some reason when I run  "sbt -DsparkVersion=3.0.1 publishLocal" the published jar only contains documentation files.

**Comment by limansky** [comment]
@etspaceman isn't this a version you're looking for https://mvnrepository.com/artifact/com.holdenkarau/spark-testing-base_2.12/3.0.0_1.0.0 ?
