### ISSUE TITLE
Publish Spark 2.4.6 and Spark 2.4.7 versions of spark-testing-base

### ISSUE THREAD

**Issue by nsutcliffe** [holdenk/spark-testing-base#337]
Hi,

Is it possible to publish a version of Spark-testing-base compiled for spark 2.4.7 (and 2.4.6 which also doesn't appear to have been published)?

Many Thanks,
Nick

**Comment by paorb156** [comment]
That would save us a ton of time currently. I second the above statement :)

**Comment by nathangrand** [comment]
Likewise
