### ISSUE TITLE
scala version 

### ISSUE THREAD

**Issue by tufanrakshit** [holdenk/spark-testing-base#338]
Hi what is the Scala version supported for this release ?
I am trying to use scala 2.12 and spark 2.4.5 version and build is failing 
[warn] 	:: com.holdenkarau#spark-testing-base_2.12;2.2.0_0.7.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.holdenkarau:spark-testing-base_2.12:2.2.0_0.7.2 (/Users/admin/Documents/workplace/projects/input-validator-master/build.sbt#L33-46)
[warn] 		  +- com.zooz:input-validator_2.12:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.holdenkarau#spark-testing-base_2.12;2.2.0_0.7.2: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)

**Comment by drobert** [comment]
You can find the release versions here: https://mvnrepository.com/artifact/com.holdenkarau/spark-testing-base

Version 2.2.0 does not seem to have been compiled for scala newer than 2.11.

Conversely, you can probably upgrade to any of the `2.4.5` versions, e.g. `2.4.5_1.1.1` which was compiled for scala 2.12.
