### ISSUE TITLE
'java.io.FileNotFoundException: HADOOP_HOME and hadoop.home.dir are unset'

### ISSUE THREAD

**Issue by shikhil-gupta** [holdenk/spark-testing-base#345]
Hi Team, I am facing this issue while running build on Build Agents. I cant set these Environment Variable on Agent pool as it is not allowed. 

Is there any way we can turn off dependency on HADOOP while running unit test?

**Comment by shikhil-gupta** [comment]
@holdenk Can you please help here?

**Comment by holdenk** [comment]
hmm maybe add to a shell script
