### ISSUE TITLE
Add cross support for Scala 2.13

### ISSUE THREAD

**Issue by Wosin** [holdenk/spark-testing-base#347]
Spark 3.2.0 has [introduced](https://issues.apache.org/jira/browse/SPARK-34218) support for Scala 2.13. It's not yet considered producion ready, but it could be a good idea to explore possibility of cross building for scala 2.13 along with 2.12.

**Comment by skestle** [comment]
@Wosin why do you think it's not production ready?
https://issues.apache.org/jira/browse/SPARK-25075 doesn't seem to mention this idea.

**Comment by tculshaw** [comment]
+1 here for scala 2.13 also for spark 3.2.1.
evaluating how far we can go up the version chain - test cases may also be run on Scala 3 !

**Comment by jelmerk** [comment]
+1

**Comment by holdenk** [comment]
Added 2.13 support in the current dev branch will be in the next release.

**Comment by tculshaw** [comment]
That is AMAZING thankyou! I'll test ASAP:)
