### ISSUE TITLE
Log4J dependency issue

### ISSUE THREAD

**Issue by Aditya-Amgaonkar** [holdenk/spark-testing-base#351]
I am trying to eliminate a transitive dependency of log4j v1.2.17 from my scala gradle project.

In order to do this I have excluded log4j dependency from my build.gradle `exclude group: "log4j", module: "log4j"` and I intend to replace this with log4j-core.

However, it seems that [spark-testing-base](https://github.com/holdenk/spark-testing-base) is not taking log4j-core automatically for its transitive dependencies. Can we fix this please?
Thanks.
<img width="969" alt="Screenshot 2022-04-26 at 9 47 35 PM" src="https://user-images.githubusercontent.com/8436553/165346430-7721bb7b-3ee7-4737-9aaf-4b33c3e6f13d.png">

**Comment by holdenk** [comment]
This seems like a gradle build issue.
