### ISSUE TITLE
netty: java.lang.NoSuchMethodError:'void io.netty.buffer.PooledByteBufAllocator.<init>(boolean, int, int, int, int, int, int, boolean)'

### ISSUE THREAD

**Issue by arumallap7** [holdenk/spark-testing-base#353]
We get the below error with sbt config. Can you guys get us a new jar with fix please ?

val sparkVersion = "3.2.1"

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % sparkVersion %Provided,
  "org.apache.spark" %% "spark-sql" % sparkVersion %Provided,
  "org.codehaus.janino" % "janino" % "3.0.7" % Test , // Defined dependency to avoid de.unkrig.jdisasm.Disassembler exception
  "com.holdenkarau" %% "spark-testing-base" % s"3.2.1_1.1.1" % Test,
  "org.apache.spark" %% "spark-hive" % sparkVersion % Test
)

[error] Uncaught exception when running analytics.commons.spark.syntax.RowOpsSpec: java.lang.NoSuchMethodError: 'void io.netty.buffer.PooledByteBufAllocator.<init>(boolean, int, int, int, int, int, int, boolean)'
[error] sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: 'void io.netty.buffer.PooledByteBufAllocator.<init>(boolean, int, int, int, int, int, int, boolean)'
[error]         at org.apache.spark.network.util.NettyUtils.createPooledByteBufAllocator(NettyUtils.java:171)
[error]         at org.apache.spark.network.util.NettyUtils.getSharedPooledByteBufAllocator(NettyUtils.java:142)
[error]         at org.apache.spark.network.client.TransportClientFactory.<init>(TransportClientFactory.java:111)
[error]         at org.apache.spark.network.TransportContext.createClientFactory(TransportContext.java:142)
[error]         at org.apache.spark.rpc.netty.NettyRpcEnv.<init>(NettyRpcEnv.scala:77)
[error]         at org.apache.spark.rpc.netty.NettyRpcEnvFactory.create(NettyRpcEnv.scala:493)
[error]         at org.apache.spark.rpc.RpcEnv$.create(RpcEnv.scala:57)
[error]         at org.apache.spark.SparkEnv$.create(SparkEnv.scala:268)
[error]         at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:191)
[error]         at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:277)
[error]         at org.apache.spark.SparkContext.<init>(SparkContext.scala:460)
[error]         at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2690)
[error]         at com.holdenkarau.spark.testing.SharedSparkContext.beforeAll(SharedSparkContext.scala:44)
[error]         at com.holdenkarau.spark.testing.SharedSparkContext.beforeAll$(SharedSparkContext.scala:38)
[error]         at analytics.commons.spark.syntax.RowOpsSpec.com$holdenkarau$spark$testing$DataFrameSuiteBase$$super$beforeAll(RowOpsSpec.scala:9)
[error]         at com.holdenkarau.spark.testing.DataFrameSuiteBase.beforeAll(DataFrameSuiteBase.scala:38)
[error]         at com.holdenkarau.spark.testing.DataFrameSuiteBase.beforeAll$(DataFrameSuiteBase.scala:37)
[error]         at analytics.commons.spark.syntax.RowOpsSpec.beforeAll(RowOpsSpec.scala:9)
[error]         at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
[error]         at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[error]         at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[error]         at analytics.commons.spark.syntax.RowOpsSpec.run(RowOpsSpec.scala:9)
[error]         at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[error]         at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[error]         at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by holdenk** [comment]
Yup we've got a fix for mismatched netty in Spark 3.2.1 will be in the next release.
