### ISSUE TITLE
Support JDK17

### ISSUE THREAD

**Issue by holdenk** [holdenk/spark-testing-base#358]

**Comment by edmondop** [comment]
Happy to look into this @holdenk . Sounds like we should enforce a more sophisticated matrix in the Github pipelines?

**Comment by holdenk** [comment]
I think there are some additional requirements for making it work as well (and probably only bother for Spark 3.4) but I have not had time (JDK17 is not a personal priority right now).

**Comment by edmondop** [comment]
Should be good now. Let me know if there are other issues that you think are urgent where I can give an hand
