### ISSUE TITLE
Defining Equality object used in StreamingSuiteBase.verifyOutput

### ISSUE THREAD

**Issue by PCejrowski** [holdenk/spark-testing-base#36]
I wonder, whether it would be possible to pass my own `Equality` object that is used in `StreamingSuiteBase` for triple-equals comparison. 
If not, could you please provide an example on how to `testOperation`, when some fields of `expectedOutput` are unknown/unimportant(e.g. time-dependent).

**Comment by holdenk** [comment]
That sounds like a good idea - @mahmoudhanafy have some time to look at this or want me to take a crack at it?

**Comment by PCejrowski** [comment]
As a workaround, I provided wrapping function, which maps right output `case class` into `case class` with limited number of fields, so that equality is checked only for those fields.

**Comment by mahmoudhanafy** [comment]
@holdenk I will have a look at it.

**Comment by holdenk** [comment]
Should be fixed in master now :)

**Comment by PCejrowski** [comment]
Thank you :)
