### ISSUE TITLE
Need builds for Spark 1.5.2 and 1.6.0

### ISSUE THREAD

**Issue by blbradley** [holdenk/spark-testing-base#38]
How can we help?

**Comment by holdenk** [comment]
If you've got some time you could update your build.sbt to 1.5.2 & 1.6.0 respectively and ensure that it builds correctly. If there aren't any issues you can add the versions to mini-cross-build.pl (sorry its ugly) and then I'll republish it.

**Comment by movermeyer** [comment]
I believe this has been completed.
