### ISSUE TITLE
typo in sbt dependency 

### ISSUE THREAD

**Issue by RAbraham** [holdenk/spark-testing-base#39]
Hi Holden,
I think the sbt dependency string in the documentation is incorrect? i.e.
```
"com.holdenkarau" % "spark-testing-base" %% "1.3.0_0.2.0"
```
What worked for me was:
```
"com.holdenkarau" %% "spark-testing-base" % "1.3.0_0.2.0"
```

**Comment by holdenk** [comment]
Ah yes, would you want to make a pull request fixing the documentation? We could also probably update it to a more recent version.
