### ISSUE TITLE
Testing Spark Actions

### ISSUE THREAD

**Issue by jnadler** [holdenk/spark-testing-base#4]
Any thoughts about testing an action?   Because an action wouldn't return anything, it doesn't exactly fit the current SparkTestingBase.   

It would still be useful to be able to use the framework for setup/execution/teardown to be able to test code like this, using mocks to verify expectations:

```
  def doAction(kafkaStream: DStream[(String, BaseEvent)]) {
    kafkaStream.foreachRDD(rdd => {
      rdd.foreachPartition(partition => {
        // code under test
      })
    })
  }
```

**Comment by holdenk** [comment]
That sounds reasonable. Do you want to add this API or should I? Sorry for my slow response on stuff I just moved recently so I've been slacking a bit.

**Comment by jnadler** [comment]
No worries.   I already made one & put it up on our internal maven repo.   My spark internals are still beginner grade, so it's a hack-and-slash job, a cut down version of the existing SparkTestingBase that I called SparkActionBase.   

I'll send a PR when I can & you will likely have ideas for improvement.

**Comment by holdenk** [comment]
Awesome, I see the PR and I'll take a look through it this weekend :)
