### ISSUE TITLE
multisets dependency locked to _2.10 version

### ISSUE THREAD

**Issue by sgt** [holdenk/spark-testing-base#41]
In `build.sbt`, please replace the line

    "io.github.nicolasstucki" % "multisets_2.10" % "0.1",

with

    "io.github.nicolasstucki" %% "multisets" % "0.3",

Otherwise, useSets support is broken on Scala 2.11.

**Comment by holdenk** [comment]
Sounds good, want to make a pull request?

On Friday, January 15, 2016, Sergei Barbarash <notifications@github.com>
wrote:

> In buildsbt, please replace the line
>
> "iogithubnicolasstucki" % "multisets_210" % "01",
>
> with
>
> "iogithubnicolasstucki" %% "multisets" % "03",
>
> Otherwise, useSets support is broken on Scala 211
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holdenk/spark-testing-base/issues/41>.
>


-- 
Cell : 425-233-8271
Twitter: https://twitter.com/holdenkarau

**Comment by sgt** [comment]
done

**Comment by holdenk** [comment]
Thanks :)
