### ISSUE TITLE
Add DataFrame generator for ScalaTest

### ISSUE THREAD

**Issue by holdenk** [holdenk/spark-testing-base#56]
Similar to how we have an RDDGenerator we should add DataFrame generators for use with ScalaTest.

As part of this, it would likely be useful to have a function which takes a DataFrame schema and turns it into a basic set of generators the DataFrame generator could use and then the user could customize it somewhat (for example if their DataFrame had Strings and Integers taking in the schema and producing a Map of column name to a string generator and integer generator) and then if the user wanted to add some constraints (e.g. non-empty strings) they could do that rather than having to specify everything. This could also be done as a separate follow up issue however.

**Comment by mahmoudhanafy** [comment]
I think the remaining part here is: 
Give the user the ability to control some specific fields.
