### ISSUE TITLE
upload module to pypi?

### ISSUE THREAD

**Issue by chiptip** [holdenk/spark-testing-base#60]
do you have plans to upload spark-testing-base onto pypi (python package index)?

**Comment by holdenk** [comment]
That's a really good suggestion, want to make an issue for it on our GitHub
and I'll look at trying to do that for our next release?

On Monday, February 15, 2016, Sonny Kwok <notifications@github.com> wrote:

> do you have plans to upload spark-testing-base onto pypi (python package
> index)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holdenk/spark-testing-base/issues/60>.
>


-- 
Cell : 425-233-8271
Twitter: https://twitter.com/holdenkarau

**Comment by holdenk** [comment]
Oh wait this was an issue (early morning before coffee). Yes I'll try and do this for the next release. Any specific Python testing functionality you want to see for the next release?

**Comment by chiptip** [comment]
thanks for the quick response!  I didn't see another issue for uploading this package to pypi.

As to python testing functionality, it would be nice to be able to test output operation, in addition to transformation functions.

http://spark.apache.org/docs/1.5.2/streaming-programming-guide.html#output-operations-on-dstreams

**Comment by Stibbons** [comment]
Hello,

I took the liberty to integrate the current version of your great unit test casses in Pypi, because I needed it to be packaged for internal projects: https://pypi.python.org/pypi/spark-testing-base

I can give you full admin rights (don't know if ownership is transferable) if you want.

**Comment by holdenk** [comment]
That would be awesome - thanks :)

On Mon, Jun 27, 2016 at 9:29 AM, Gaetan Semet <notifications@github.com>
wrote:

> Hello,
>
> I took the liberty to integrate the current version of your great unit
> test casses in Pypi, because I needed it to be packaged for internal
> projects: https://pypi.python.org/pypi/spark-testing-base
>
> I can give you full admin rights (don't know if ownership is transferable)
> if you want.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/holdenk/spark-testing-base/issues/60#issuecomment-228798869>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AADp9V6ZNv0FELIfHsWkNaqwgNZEigPDks5qP_pigaJpZM4Hah-t>
> .
>



-- 
Cell : 425-233-8271
Twitter: https://twitter.com/holdenkarau

**Comment by holdenk** [comment]
I can also add you as a contributor to the github repo if that would be
useful for you.

On Mon, Jun 27, 2016 at 12:10 PM, Holden Karau <holden@pigscanfly.ca> wrote:

> That would be awesome - thanks :)
>
> On Mon, Jun 27, 2016 at 9:29 AM, Gaetan Semet <notifications@github.com>
> wrote:
>
>> Hello,
>>
>> I took the liberty to integrate the current version of your great unit
>> test casses in Pypi, because I needed it to be packaged for internal
>> projects: https://pypi.python.org/pypi/spark-testing-base
>>
>> I can give you full admin rights (don't know if ownership is
>> transferable) if you want.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/holdenk/spark-testing-base/issues/60#issuecomment-228798869>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AADp9V6ZNv0FELIfHsWkNaqwgNZEigPDks5qP_pigaJpZM4Hah-t>
>> .
>>
>
>
>
> --
> Cell : 425-233-8271
> Twitter: https://twitter.com/holdenkarau
>



-- 
Cell : 425-233-8271
Twitter: https://twitter.com/holdenkarau

**Comment by Stibbons** [comment]
Please send me a mail at gaetan[at]xeberon.net for creds. I don't know if I will do pull requests to this project, even if forking it the way I did was actually useful. But sure if I have change I'll make PR :)

**Comment by holdenk** [comment]
This is finally being uploaded on PyPi  - closing the issue for now :)
