### ISSUE TITLE
equalDataFrames should not call  DataFrameSuiteBaseLike.approxEquals directly.

### ISSUE THREAD

**Issue by matmsh** [holdenk/spark-testing-base#72]
Hi,
 I am using
 "com.holdenkarau"   %% "spark-testing-base"          % "1.5.2_0.3.0"

In  the trait  DataFrameSuiteBaseLike , there is  the  method
 def approxEquals(r1: Row, r2: Row, tol: Double): Boolean = {
    DataFrameSuiteBase.approxEquals(r1, r2, tol)
  }

    https://github.com/holdenk/spark-testing-base/blob/master/src/main/1.3/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala
  
  
The methods    DataFrameSuiteBaseLike.equalDataFrames and 
approxEqualDataFrames call  DataFrameSuiteBase.approxEquals(r1, r2, tol) directly.

Shouldn't   DataFrameSuiteBaseLike.equalDataFrames and 
approxEqualDataFrames calls  DataFrameSuiteBaseLike.approxEquals  ?

As it is, overriding 
DataFrameSuiteBaseLike.approxEquals has no effect.

Shing

**Comment by mahmoudhanafy** [comment]
`equalDataFrames` and `approxEqualDataFrames` uses `DataFrameSuiteBase.approxEquals` for some serialization issues. Try using `DataFrameSuiteBaseLike.approxEquals` and run the tests. 

I just created method `DataFrameSuiteBaseLike.approxEquals` to test method `DataFrameSuiteBase.approxEquals` easily, by calling `approxEquals` directly in tests.

Note: `DataFrameSuiteBaseLike.approxEquals` and `DataFrameSuiteBase.approxEquals` are not overriding each other. They are two separate methods
