### ISSUE TITLE
DataFrameSuiteBase not working

### ISSUE THREAD

**Issue by jerrypaytm** [holdenk/spark-testing-base#74]
I tried to extend the scala test with ```DataFrameSuiteBase```, the sqlContext cannot be resolved to SQLContext because it has type ```Any```. Does anyone have the same issue?

**Comment by mahmoudhanafy** [comment]
Could you add the code snippet !!

**Comment by mahmoudhanafy** [comment]
You can also apply one of the examples [here](https://github.com/holdenk/spark-testing-base/wiki/DataFrameSuiteBase). This code is working fine.

**Comment by tolomaus** [comment]
I have the same issue, just pasting the DataFrame example is sufficient to reproduce it. I would love to use the library but not sure how to get it to work

**Comment by mahmoudhanafy** [comment]
could you add the code that you use !

**Comment by mahmoudhanafy** [comment]
I tried to copy and paste the example, and I found that this line doesn't compile:
`import sqlCtx.implicits._`
And I found a relevant question [here](http://stackoverflow.com/questions/34854317/spark-scala-unable-to-import-sqlcontext-implicits). You must include spark-sql dependency to your build.sbt file.
If you have other error than this, please describe it.

**Comment by tolomaus** [comment]
Ah I see what's missing now: the library depends on spark-hive and I had to manually add this dependency to my build.sbt.

Thanks for the hint!
