### ISSUE TITLE
Errors when running several test suites from sbt with parallelExecution := true

### ISSUE THREAD

**Issue by juanrh** [holdenk/spark-testing-base#8]
Hi, 

When I run all the tests from a project with `sbt test` and I have more than one test suite involving Spark, then I get execution errors. This can be reproduced for example running `sbt test` with https://github.com/juanrh/spark-testing-base, and commenting `parallelExecution := false` in build.sbt. I guess this has to do with https://issues.apache.org/jira/browse/SPARK-2243, and it looks like a non trivial problem with Spark. I tried to use a trait and companion StaticSparkContext to use just a single Spark Context for the whole JVM, but then we wouldn't be able to use different clock configuration for different test suites, as there would be just a single SparkConf for the whole JVM. 

So for now using `parallelExecution := false` in build.sbt is a workaround, but I though it would be nice to open an issue, in case  https://issues.apache.org/jira/browse/SPARK-2243 is solved in the future, and then concurrent execution of Spark test suites is possible. Anyway I would like to hear your thoughts about this. 

Thanks again for this nice spark package. 

Greetings, 

Juan

**Comment by ghl3** [comment]
I too am running into a similar issue with my own testing suite.  If solving this depends on a deep change in Spark itself, a second-best option would be to add this description to the documentation (preferably in the top-level readme) and, if possible, to try and catch this specific exception in "spark-testing-base" and show a nicer error message.

**Comment by holdenk** [comment]
For now I've just added it as a doc mention in the README, we could use concurrent SparkContexts, the singleton SparkContext would be good for the future if we can figure out the clock difference issue (I think it should be doable).
