### ISSUE TITLE
No testOperation() for binary operations in JavaStreamingSuiteBase

### ISSUE THREAD

**Issue by huylv** [holdenk/spark-testing-base#81]
Unable to run `SampleJavaStreamingTest`, there's no `testOperation` defined for binary operations. Please fix it. Thank you.

**Comment by huylv** [comment]
Turns out latest versions available on mvn central repo (`1.6.0_0.3.1`/`0.3.1`) don't have these methods. I had to build `0.3.2` from source. Please upload the latest version to mvn central. I'll leave this issue open for now.

Many thanks.

**Comment by holdenk** [comment]
I'll try and get new release out tonight.

**Comment by mahmoudhanafy** [comment]
version 0.3.2 is now available.
