### ISSUE TITLE
RDDComparisons Assert Doesn't Fail

### ISSUE THREAD

**Issue by eljefe6a** [holdenk/spark-testing-base#86]
I'm using spark-testing-base with Java. I'm using the `RDDComparisons` to compare the outputs of two RDDs. Here is the code:
```
        List<String> input = Arrays.asList("1\tHeart", "2\tDiamonds");
        JavaRDD<String> inputRDD = jsc().parallelize(input);
        JavaPairRDD<String, Integer> result = RefactoredForTests.runETL(inputRDD);

        List<Tuple2<String, Integer>> expectedInput = Arrays.asList(
                new Tuple2<String, Integer>("Heart", 1),
                new Tuple2<String, Integer>("Diamonds", 12));
        JavaPairRDD<String, Integer> expectedRDD = jsc().parallelizePairs(expectedInput);

        ClassTag<Tuple2<String, Integer>> tag = scala.reflect.ClassTag$.MODULE$.apply(Tuple2.class);
        
        // Doesn't assert failure
        RDDComparisons.compareWithOrder(JavaPairRDD.toRDD(result),
                JavaPairRDD.toRDD(expectedRDD), tag);
        
        List<Tuple2<String, Integer>> expectedList = expectedRDD.collect();
        List<Tuple2<String, Integer>> actualList = result.collect();
        
        // Does fail
        for (int i = 0; i < expectedList.size(); i++) {
            assertEquals(expectedList.get(i), actualList.get(i));
        }
```

I've manually changed the expected output to fail (should be 2 but I have a 12). Both the `compareWithOrder` and `compare` functions don't fail during the check. However, the manual check that I wrote does fail correctly.

Is there something extra to the `compare`?

**Comment by mahmoudhanafy** [comment]
`compareWithOrder` doesn't assert the results, here is the documentation of this method:
```
  /**
   * Compare two RDDs. If they are equal returns None, otherwise
   * returns Some with the first mismatch. Assumes we have the same partitioner.
   */
```

**Comment by eljefe6a** [comment]
Coming from an MRUnit background, I was thinking that `compareWithOrder` would assert.

Here is how you would assert:
```
        Option<Tuple2<Tuple2<String, Integer>, Tuple2<String, Integer>>>
        compareWithOrder =
            RDDComparisons.compareWithOrder(JavaPairRDD.toRDD(result),
                                            JavaPairRDD.toRDD(expectedRDD), tag);

        assertEquals(scala.None$.MODULE$, compareWithOrder);
```

Which gives a pretty understandable error now:
```
java.lang.AssertionError: expected:<None> but was:<Some(((Diamonds,2),(Diamonds,12)))>
```

**Comment by mahmoudhanafy** [comment]
I will create another method that assert automatically.

**Comment by mahmoudhanafy** [comment]
I created this PR #88 to add assert RDDs automatically method and to make it easier to compare RDDs in Java.

**Comment by eljefe6a** [comment]
Would be nice to have asserts on other objects like DataFrames too.

**Comment by mahmoudhanafy** [comment]
It is already existed, Have a look [here](https://github.com/holdenk/spark-testing-base/wiki/DataFrameSuiteBase).

**Comment by eljefe6a** [comment]
I mean does the `DataFrameSuiteBase` have an assert method like you just added for RDDs? When I looked at the methods, it didn't look like it. If you have assert methods for RDDs, you'll want them for other comparison objects.
