### ISSUE TITLE
Support for spark 1.4.1

### ISSUE THREAD

**Issue by jtescher** [holdenk/spark-testing-base#9]
Great library, thanks for all the hard work!

Looks like Spark is up to 1.4.x any chance of a release that supports it?

**Comment by jeremysanecki** [comment]
Super useful project. We also looking to update our existing 1.3.0 tests to 1.4.1 Spark.

**Comment by holdenk** [comment]
Sure, probably sometime this week.

**Comment by holdenk** [comment]
The latest release is now works with 1.4.1 :)

**Comment by jeremysanecki** [comment]
Thank you!
