### ISSUE TITLE
some tests got oom error

### ISSUE THREAD

**Issue by futureage** [holdenk/spark-testing-base#91]
hi,holdenk
When i tried to run test follow the wiki "DataFrameSuiteBase"(https://github.com/holdenk/spark-testing-base/wiki/DataFrameSuiteBase), i got one OOM error, but other test (DataFrameGenerator) is ok.
there is my environment:
os: centos 6.4
machine memory: 8G
jdk: 1.7.0_79
maven: apache-maven-3.3.9
MAVEN_OPTS：-Xmx2g -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512m
spark: spark-1.6.0

and this is the error:
An exception or error caused a run to abort. This may have been caused by a problematic custom reporter.
```
Exception in thread "ScalaTest-main" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ScalaTest-main"
```
thanks

**Comment by mahmoudhanafy** [comment]
Could you add the code you used for testing ?

**Comment by futureage** [comment]
thanks. I just copy the example from wiki "DataFrameSuiteBase", and do not change anything.

`class test extends DataFrameSuiteBase {
    test("simple test") {
      val sqlCtx = sqlContext
      import sqlCtx.implicits._

    val input1 = sc.parallelize(List(1, 2, 3)).toDF
    equalDataFrames(input1, input1) // equal

    val input2 = sc.parallelize(List(4, 5, 6)).toDF
    intercept[org.scalatest.exceptions.TestFailedException] {
        equalDataFrames(input1, input2) // not equal
    }
  }
}`

**Comment by futureage** [comment]
thanks, @mahmoudhanafy 
I just copy the example from wiki 'DataFrameSuiteBase', and do not change anything.

class test extends DataFrameSuiteBase {
  test("simple test") {
    val sqlCtx = sqlContext
    import sqlCtx.implicits._

    val input1 = sc.parallelize(List(1, 2, 3)).toDF
    equalDataFrames(input1, input1) // equal

    val input2 = sc.parallelize(List(4, 5, 6)).toDF
    intercept[org.scalatest.exceptions.TestFailedException] {
        equalDataFrames(input1, input2) // not equal
    }
  }
}

**Comment by mahmoudhanafy** [comment]
What is the available memory at your machine, when you try to run the test ?
Your total machine memory is 8 GB, but other processes may be consuming memory.

**Comment by holdenk** [comment]
We should probably update our documentation to mention the default JVM sizes from sbt is too small for testing - I suspect this is the issue.

**Comment by holdenk** [comment]
Try following the instructions under "Minimum Memory Requirements and OOMs" in our new README and let me know if that works for you :)

**Comment by futureage** [comment]
thanks, @holdenk , it do resolve my problem, thanks!
and thanks @mahmoudhanafy too!
