### ISSUE TITLE
Don't inherit from FunSuite in the StreamingSuite helpers.

### ISSUE THREAD

**Issue by aditanase** [holdenk/spark-testing-base#92]
Doing so prevents them being mixed in the FunSpec format of using scalatest suites.
My team has chosen FunSpec over FunSuite.

You can probably get away with inheriting from Suite or simply specifying a self type annotation on the 2 Streaming traits, just like you're doing on SharedSparkContext.

For your own tests (e.g. SampleStreamingActionTest), you can change them to inherit from FunSuite.

I tested this in a local branch, the changes seem minimum, I can send over a PR if that's easier.

**Comment by holdenk** [comment]
If you've got the code for a PR handy that would be great :)

**Comment by falloutdurham** [comment]
I hope I'm not stepping on any toes, but this was bugging me today ;)
