### ISSUE TITLE
spark.default.parallelism isn't set in SharedSparkContext

### ISSUE THREAD

**Issue by aarondaub** [holdenk/spark-testing-base#94]
It'd be nice to have spark.default.parallelism set to `1` in `SharedSparkContext`, unless there are reasons not to that I am unaware of.

**Comment by mahmoudhanafy** [comment]
Why it is better to set `spark.default.parallelism` to 1 ?

**Comment by holdenk** [comment]
That would actually be counter productive as a bunch of things might only show up with default parallelism above 1. I'm going to close this for now but if there is a compelling reason to set it to a specific value or make it easier to do this I'm open to re-open the issue.
